CC = gcc
CFLAGS = -g -Wall -I/path/to/mqtt/include
LDFLAGS = -L/path/to/mqtt/lib -lmqtt

all: tic-tac-toe

tic-tac-toe: tic-tac-toe.o
    $(CC) -o $@ $^ $(LDFLAGS)

tic-tac-toe.o: tic-tac-toe.c
    $(CC) $(CFLAGS) -c -o $@ $<

clean:
    rm -f *.o tic-tac-toe